import turtle
turtleDraw = turtle.Turtle()
def draw(b, d, w, h):
    turtleDraw.forward(w)
    turtleDraw.left(90)
    turtleDraw.forward(h)
    turtleDraw.left(90)
    turtleDraw.forward(w)
    turtleDraw.left(90)
    turtleDraw.forward(h)
    turtleDraw.right(180)
    turtleDraw.forward(h)
    turtleDraw.left(90)
    turtleDraw.forward(b)
    turtleDraw.right(135)
    turtleDraw.forward(2*b)
    turtleDraw.right(45)
    turtleDraw.forward(w)
    turtleDraw.right(45)
    turtleDraw.forward(2*b)
    turtleDraw.right(135)
    turtleDraw.forward(b)
